<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookWorm.Repository.Common\BookWorm.Repository.Common.csproj" />
    <ProjectReference Include="..\BookWorm.Repository\BookWorm.Repository.csproj" />
  </ItemGroup>

</Project>
