<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookWorm.Service.Common\BookWorm.Service.Common.csproj" />
    <ProjectReference Include="..\BookWorm.WebApi\BookWorm.WebAPI.csproj" />
  </ItemGroup>

</Project>
